language: go
sudo: required

services:
  - docker

matrix:
  include:
  - go: "1.10.x"
    script:  go test -v ./...
  - go: "1.11.x"
    script: go test -v -mod=vendor ./...
env:
  - GO111MODULE=on
install: true
script:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/fsouza/go-dockerclient
  - go get github.com/tiago4orion/conjure
  - go get golang.org/x/tools/cmd/cover
  - hack/check.sh
#  - goveralls -coverprofile=coverage.txt -service=travis-ci
before_install:
  - sudo pip install codecov
after_success:
  codecov
